<?php
session_start();
include('includes/db.php');

if (!isset($_SESSION['admin_user'])) {
    die("Error: Employee ID not found in session.");
}

$UserID = $_SESSION['admin_user'];

// Fetch employee details
$sql = "SELECT FName, LName, ProfilePicture FROM admintbl WHERE UserID = ?";
$stmt = $conn->prepare($sql);

if ($stmt) {
    $stmt->bind_param("s", $UserID);
    $stmt->execute();
    $result = $stmt->get_result();
    $employee = $result->fetch_assoc();
    $stmt->close();
} else {
    die("Error in SQL query: " . $conn->error);
}

// Validate fetched employee data for sidebar
$fullName = isset($employee['FName']) ? $employee['FName'] . ' ' . $employee['LName'] : 'Unknown User';
$profilePicture = (!empty($employee['ProfilePicture'])) ? $employee['ProfilePicture'] : "src/default.jpg";


// Fetch leave reports for pagination
$recordsPerPage = 15; // Number of records to display per page
$currentPage = isset($_GET['page']) ? (int)$_GET['page'] : 1; // Current page number
$startIndex = ($currentPage - 1) * $recordsPerPage; // Calculate the starting index

// Fetch total number of leave reports
$totalEntriesQuery = "SELECT COUNT(*) as total FROM leavetable";
$totalEntriesResult = $conn->query($totalEntriesQuery);
$totalEntries = $totalEntriesResult->fetch_assoc()['total'];

// Calculate total pages
$totalPages = ceil($totalEntries / $recordsPerPage);

// Fetch leave reports with pagination
$sql = "SELECT lt.*, et.FName, et.LName 
    FROM leavetable lt
    JOIN employeedetail et ON lt.EmployeeID = et.EmployeeID
    LIMIT ?, ?";
$stmt = $conn->prepare($sql);

if ($stmt) {
    $stmt->bind_param("ii", $startIndex, $recordsPerPage);
    $stmt->execute();
    $result = $stmt->get_result();
} else {
    die("Error in SQL query: " . $conn->error);
}

// Leave report filtering by date
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['filter'])) {
    $fromDate = $_POST['from'];
    $toDate = $_POST['to'];

    $sql = "SELECT lt.*, et.FName, et.LName 
            FROM leavetable lt
            JOIN employeedetail et ON lt.EmployeeID = et.EmployeeID
            WHERE lt.StartDate >= ? AND lt.EndDate <= ?
            LIMIT ?, ?";
    $stmt = $conn->prepare($sql);

    $alertMessage = ""; // Default value

    if ($stmt) {
        $stmt->bind_param("ssii", $fromDate, $toDate, $startIndex, $recordsPerPage);
        $stmt->execute();
        $result = $stmt->get_result();
    
        if ($result->num_rows === 0) {
            $alertMessage = "No leave request data found for the selected date range.";
        }
    } else {
        die("Error in SQL query: " . $conn->error);
    }
    
}

// Generate PDF report
if (isset($_POST['generate_report'])) {
    require_once 'tcpdf/tcpdf.php';

    $fromDate = $_POST['from'];
    $toDate = $_POST['to'];

    $sql = "SELECT lt.*, et.FName, et.LName 
            FROM leavetable lt
            JOIN employeedetail et ON lt.EmployeeID = et.EmployeeID
            WHERE lt.StartDate >= ? AND lt.EndDate <= ?";
    $stmt = $conn->prepare($sql);

    if ($stmt) {
        $stmt->bind_param("ss", $fromDate, $toDate);
        $stmt->execute();
        $result = $stmt->get_result();

        $pdf = new TCPDF('P', 'mm', 'A4', true, 'UTF-8', false);
        $pdf->SetMargins(10, 10, 10);
        $pdf->AddPage();
        $pdf->SetFont('times', 'B', 12);
        $pdf->Cell(0, 10, 'Employee Management System Leave Report', 0, 1, 'C');
        $pdf->Ln(5);

        $pdf->SetFont('times', '', 10);
        $pdf->SetFillColor(240, 240, 240);
        $pdf->Cell(40, 8, 'Name', 1, 0, 'C', 1);
        $pdf->Cell(25, 8, 'Start Date', 1, 0, 'C', 1);
        $pdf->Cell(25, 8, 'End Date', 1, 0, 'C', 1);
        $pdf->Cell(30, 8, 'Type', 1, 0, 'C', 1);
        $pdf->Cell(50, 8, 'Reason', 1, 0, 'C', 1);
        $pdf->Cell(25, 8, 'Status', 1, 1, 'C', 1);

        if ($result->num_rows > 0) {
            while ($row = $result->fetch_assoc()) {
                $pdf->Cell(40, 8, $row['FName'] . ' ' . $row['LName'], 1);
                $pdf->Cell(25, 8, date("F j, Y", strtotime($row['StartDate'])), 1);
                $pdf->Cell(25, 8, date("F j, Y", strtotime($row['EndDate'])), 1);
                $pdf->Cell(30, 8, $row['LeaveType'], 1);
                $pdf->Cell(50, 8, $row['Reason'], 1);
                $pdf->Cell(25, 8, $row['Status'], 1, 1);
            }
        } else {
            $pdf->Cell(195, 10, 'No leave records found for the selected date range.', 1, 1, 'C');
        }

        // Add footer
        $pdf->Ln(10);
        $pdf->SetFont('times', 'I', 10);
        $pdf->Cell(0, 10, 'Generated by Penthouse - Employee Management System', 0, 1, 'C');

        ob_end_clean();
        $pdf->Output('EMS Leave_Report.pdf', 'D');
        exit;
    } else {
        die("Error in SQL query: " . $conn->error);
    }
}

// Notification Process
$sql = "SELECT l.ID, l.Status, l.AppliedDate, ns.AdminIsRead, CONCAT(e.FName, ' ', e.LName) AS EmployeeName 
    FROM Leavetable l
    LEFT JOIN leave_notification_status ns ON l.ID = ns.LeaveID
    LEFT JOIN employeedetail e ON l.EmployeeID = e.EmployeeID
    ORDER BY l.AppliedDate DESC
    LIMIT 5"; // Limit to 5 most recent notifications
$notificationResult = $conn->query($sql);

if (!$notificationResult) {
    die("Error in SQL query: {$conn->error}");
}

// Mark notifications as read when the dropdown is opened
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['markAllRead'])) {
    // Update all notifications to 'read' (AdminIsRead = 1)
    $updateSql = "UPDATE leave_notification_status SET AdminIsRead = 1";
    if (!$conn->query($updateSql)) {
        die("Error in SQL query: {$conn->error}");
    }
    // Return success response
    echo json_encode(['success' => true]);
    exit;
}

//End of Notification Process


?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/x-icon" href="src/favicon-logo.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="includes/dashboard.css">
    <link rel="stylesheet" href="includes/adminDashboard.css">
    <link rel="stylesheet" href="includes/AdminLeaveReport.css">
    <script src="includes/AdminLeaveReport.js"></script>
    <script src="includes/adminDashboard.js"></script>
    <!-- Font Awesome for icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <title>TCU EMS</title>
</head>
<body>

<!-- Sidebar -->
<div class="sidebar">
    <div class="logo-container">
        <img src="src/tcu-logo.png" alt="TCU Logo" class="logo">
        <span class="university-name">Taguig City University</span>
    </div>
    <div class="profile-section">
        <img src="<?= $profilePicture; ?>" alt="Profile Picture" class="profile-image">
        <div class="profile-details">
            <span class="profile-name"><?= htmlspecialchars($fullName); ?></span>
            <span class="profile-role">Administrator</span>
        </div>
    </div>
    <div class="sidebar-menu">
        <a href="adminDashboard.php" class="menu-item ">
            <span class="icon icon-dashboard"></span> Dashboard
        </a>
        <div class="dropdown">
    <a href="#" class="menu-item dropdown-toggle">
        <span class="icon icon-employee"></span> Employees
        <span class="icon icon-right-arrow"></span>
    </a>
    <div class="dropdown-content">
        <a href="addEmployee.php" class="dropdown-item">Add Employee</a>
        <a href="viewEmployees.php" class="dropdown-item">View Employees</a>
    </div>
</div>

<div class="dropdown">
    <a href="#" class="menu-item dropdown-toggle active">
        <span class="icon icon-reports"></span> Reports
        <span class="icon icon-right-arrow"></span>
    </a>
    <div class="dropdown-content">
        <a href="AdminLeaveReports.php" class="dropdown-item">Leave Reports</a>
        <a href="AdminScheduleReports.php" class="dropdown-item">Schedule Reports</a>
    </div>
</div>

        <a href="adminSchedule.php" class="menu-item">
            <span class="icon icon-schedule"></span> Schedule
        </a>
        <a href="AdminSettings.php" class="menu-item">
            <span class="icon icon-settings"></span> Settings
        </a>
    </div>
    <a href="index.html" class="logout">
        <span class="icon icon-logout"></span> Log out
    </a>
</div>
    <!-- End of the Sidebar -->
<div class="main-content">
 <!-- Header -->
 <div class="header">
        <h1 class="header-title">Leave Report</h1>
        <div class="header-actions">
            <!-- Search Container -->
            <div class="search-container">
    <span class="icon icon-search"></span>
    <input type="text" class="search-input" id="searchInput" placeholder="Search anything here" onkeyup="searchTable()">
</div>

<!-- Notification -->
<div class="notif-dropdown">
    <span class="icon icon-notification header-icon" id="notificationDropdown"></span>
    <span id="unreadCount" class="unread-count"><?= $notificationResult->num_rows; ?></span> <!-- Unread count -->
    <div class="dropdown-content notification-dropdown">
        <div class="notification-header">
            <h3>Notifications</h3>
            <span class="mark-all-read" id="markAllRead">Mark all as read</span>
        </div>
        <?php 
        $hasValidNotifications = false;
        if ($result->num_rows > 0): 
        ?>
            <?php while ($row = $notificationResult->fetch_assoc()): ?>
                <?php $hasValidNotifications = true; ?>
                <div class="notification-item <?= ($row['AdminIsRead'] == 0) ? 'unread' : 'read'; ?>" id="notif-<?= $row['ID']; ?>">
                    <div class="notification-icon <?= ($row['Status'] === 'Approved') ? 'notification-icon-leave' : (($row['Status'] === 'Rejected') ? 'notification-icon-rejected' : 'notification-icon-pending'); ?>">
                        <!-- Font Awesome icons for approved, rejected, and pending status -->
                        <?php if ($row['Status'] === 'Approved'): ?>
                            <i class="fa fa-check"></i> <!-- Green checkmark for approved -->
                        <?php elseif ($row['Status'] === 'Rejected'): ?>
                            <i class="fa fa-times"></i> <!-- Red cross for rejected -->
                        <?php else: ?>
                            <i class="fa fa-hourglass-half"></i> <!-- Clock icon for pending -->
                        <?php endif; ?>
                    </div>
                    <div class="notification-content">
                        <p>
                            <?= htmlspecialchars($row['EmployeeName']); ?> 
                            <?= ($row['Status'] === 'Approved') 
                                ? 'had their leave request approved.' 
                                : (($row['Status'] === 'Rejected') 
                                    ? 'had their leave request rejected.' 
                                    : 'has a pending leave request.'); ?>
                        </p>
                        <span class="notification-time">
                            <?= 'Applied on: ' . date('F j, Y', strtotime($row['AppliedDate'])); ?>
                        </span>
                    </div>
                </div>
            <?php endwhile; ?>
        <?php endif; ?>
        <?php if (!$hasValidNotifications): ?>
            <div class="notification-item">
                <div class="notification-content">
                    <p>No notifications available</p>
                </div>
            </div>
        <?php endif; ?>
        <a href="#" class="view-all-notifications" id="viewAllNotifications">View all notifications</a>
    </div>
</div>
<!-- End of Notification -->
<!-- Modal for all notifications -->
<div id="allNotificationsModal" class="modal">
    <div class="modal-content">
        <span class="close-modal" id="closeModal">&times;</span>
        <h2>All Notifications</h2>

        <div class="all-notifications-list">
            <?php 
            $allNotificationsSql = "SELECT l.ID, l.Status, l.AppliedDate, ns.IsRead, CONCAT(e.FName, ' ', e.LName) AS EmployeeName 
                                    FROM Leavetable l
                                    LEFT JOIN leave_notification_status ns ON l.ID = ns.LeaveID
                                    LEFT JOIN employeedetail e ON l.EmployeeID = e.EmployeeID
                                    WHERE l.Status IN ('Approved', 'Rejected', 'Pending')
                                    ORDER BY l.AppliedDate DESC";
            $allStmt = $conn->prepare($allNotificationsSql);
            if ($allStmt) {
                $allStmt->execute();
                $allResult = $allStmt->get_result();
                if ($allResult->num_rows > 0) {
                    while ($row = $allResult->fetch_assoc()): ?>
                        <div class="notification-item ">
                            <div class="notification-icon <?= ($row['Status'] === 'Approved') ? 'notification-icon-leave' : (($row['Status'] === 'Rejected') ? 'notification-icon-rejected' : 'notification-icon-pending'); ?>">
                                <?php if ($row['Status'] === 'Approved'): ?>
                                    <i class="fa fa-check"></i>
                                <?php elseif ($row['Status'] === 'Rejected'): ?>
                                    <i class="fa fa-times"></i>
                                <?php else: ?>
                                    <i class="fa fa-hourglass-half"></i>
                                <?php endif; ?>
                            </div>
                            <div class="notification-content">
                                <p>
                                    <?= htmlspecialchars($row['EmployeeName']); ?> 
                                    <?= ($row['Status'] === 'Approved') 
                                        ? 'had their leave request approved.' 
                                        : (($row['Status'] === 'Rejected') 
                                            ? 'had their leave request rejected.' 
                                            : 'has a pending leave request.'); ?>
                                </p>
                                <span class="notification-time">
                                    <?= 'Applied on: ' . date('F j, Y', strtotime($row['AppliedDate'])); ?>
                                </span>
                            </div>
                        </div>
                    <?php endwhile;
                } else { ?>
                    <div class="no-notifications-message">
                        No notifications available
                    </div>
                <?php }
                $allStmt->close();
            } else { ?>
                <div class="no-notifications-message">
                    Error fetching notifications.
                </div>
            <?php } ?>
        </div>
        <button id="clearNotificationsBtn" class="clear-notifications-btn">Clear Notifications</button>
    </div>
</div>
<!-- End of Notification Modal -->
  <!-- Profile Dropdown -->
            <div class="Profile-dropdown">
                <button class="Pdropdown-button">
                    <img src="<?= $profilePicture; ?>" alt="Profile" class="profile-icon">
                </button>
                <div class="Pdropdown-content">
                    <a href="AdminSettings.php">Settings</a>
                    <a href="index.html">Log out</a>
                </div>
            </div>
            <!-- End of Profile Dropdown -->
        </div>
    </div>
    <!-- End of the Header -->
<?php if (!empty($alertMessage)): ?>
    <div class="alert alert-warning" id="alertMessage">
        <?= htmlspecialchars($alertMessage) ?>
    </div>

    <script>
      // Auto-hide alert after 5 seconds (5000 ms)
      setTimeout(function () {
        const alertBox = document.getElementById("alertMessage");
        if (alertBox) {
          alertBox.style.transition = "opacity 0.5s ease";
          alertBox.style.opacity = 0;
          setTimeout(() => alertBox.style.display = "none", 500); // hide after fade out
        }
      }, 5000);
    </script>
<?php endif; ?>

<!-- Table -->
<div class="schedule-container">
            <div class="schedule-header">
                <!--ENTRIES-->
                <div class="schedule-controls">
                    <div class="entries-control">
                        <span>Show</span>
                        <select id="entriesDropdown" onchange="changeEntries(this.value)">
                            <option value="15" >15</option>
                            <option value="25" >25</option>
                            <option value="50" >50</option>
                            <option value="100" >100</option>
                        </select>
                        <span>entries</span>
                    </div>
                    
                    <form method="POST">
  <div class="date-filter">
    <label for="from">From</label>
    <input type="date" id="from" name="from" required>

    <label for="to">To</label>
    <input type="date" id="to" name="to" required>

    <!-- Submit for filtering -->
    <button type="submit" name="filter" class="filter-btn">
      <i class="fas fa-search"></i> Filter by Date
    </button>

    <!-- Submit for report -->
    <button type="submit" name="generate_report" class="report-btn">
      <i class="fas fa-download"></i> Generate Report
    </button>
  </div>
</form>


                </div>

            </div>
<!-- END FILTER CONTROL -->
            <!--TABLE-->
            <div class="schedule-table-container">
    <table class="schedule-table" id="dataTable">
    <thead>
        <tr>
            <th>Name</th>
            <th>Duration(s)</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Type</th>
            <th>Reason</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php if ($result->num_rows > 0): ?>
            <?php while ($row = $result->fetch_assoc()): ?>
            <tr>
                <td><?= htmlspecialchars($row['FName'] . ' ' . $row['LName']) ?></td>
                <td><?= htmlspecialchars($row['Duration']) ?> Day(s)</td>
                <td><?= htmlspecialchars(date("F j, Y", strtotime($row['StartDate']))) ?></td>
                <td><?= htmlspecialchars(date("F j, Y", strtotime($row['EndDate']))) ?></td>
                <td><?= htmlspecialchars($row['LeaveType']) ?></td>
                <td><?= htmlspecialchars($row['Reason']) ?></td>
                <td>
                    <?php 
                        $status = isset($row['Status']) ? $row['Status'] : 'N/A';
                        $statusClass = ($status == 'Approved') ? 'status-approved' :
                                       (($status == 'Pending') ? 'status-pending' :
                                       (($status == 'Rejected') ? 'status-rejected' : 'status-unknown'));
                    ?>
                    <span class="status-badge <?php echo $statusClass; ?>"><?php echo htmlspecialchars($status); ?></span>
                </td>
            </tr>
            <?php endwhile; ?>
        <?php else: ?>
            <tr><td colspan="7">No leave records found.</td></tr>
        <?php endif; ?>
    </tbody>
</table>

</div>

<div class="pagination-info">
    Showing <?php echo ($totalEntries > 0) ? ($startIndex + 1) : 0; ?> to 
    <?php echo min($startIndex + $recordsPerPage, $totalEntries); ?> 
    of <?php echo $totalEntries; ?> entries
</div>

<div class="pagination">
    <button class="pagination-btn" <?php echo ($currentPage <= 1) ? 'disabled' : ''; ?> 
        onclick="changePage(<?php echo max(1, $currentPage - 1); ?>)">
        Previous
    </button>
    
    <?php for ($i = 1; $i <= $totalPages; $i++): ?>
        <button class="pagination-btn <?php echo ($i == $currentPage) ? 'active' : ''; ?>" 
            onclick="changePage(<?php echo $i; ?>)">
            <?php echo $i; ?>
        </button>
    <?php endfor; ?>

    <button class="pagination-btn" <?php echo ($currentPage >= $totalPages) ? 'disabled' : ''; ?> 
        onclick="changePage(<?php echo min($totalPages, $currentPage + 1); ?>)">
        Next
    </button>
</div>

        </div>
          <!--END OF TABLE-->

<!-- End of main content -->
</div>
<script src="includes/adminHeader.js"></script>
</body>
</html>
